Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -44,13 +44,15 @@ steps:
       ]
     id: apply-deploy-config
 
-  # Step 5: Create Release and save release name
+ # Step 5: Create Release and save release name
   - name: 'gcr.io/cloud-builders/gcloud'
     entrypoint: 'bash'
     args:
       - '-c'
       - |
         RELEASE_NAME="amjad-release-$(date +%Y%m%d%H%M%S)"
+        echo "Generated release name: $$RELEASE_NAME"  # Debugging log
+
         echo $$RELEASE_NAME > /workspace/release-name.txt
 
         gcloud deploy releases create $$RELEASE_NAME \
@@ -58,6 +60,10 @@ steps:
           --region=asia-east1 \
           --delivery-pipeline=amjad-pipeline \
           --images=amjad-image=asia-east1-docker.pkg.dev/enhub-cloud-interns/amjad-artifact-cloudrun/amjad-image:latest
+        if [ $? -ne 0 ]; then
+          echo "Failed to create release."
+          exit 1
+        fi
     id: create-release
     waitFor: ['apply-deploy-config']
 
